### ISSUE TITLE
SyntaxError: reserved word "function"

### ISSUE THREAD

**Issue by GabLeRoux** [hubot-scripts/hubot-github-repo-event-notifier#29]
Using version `1.5.0`, I get this error:

```
hubot> [Fri Sep 18 2015 22:48:49 GMT-0400 (EDT)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Fri Sep 18 2015 22:48:49 GMT-0400 (EDT)] ERROR Unable to load /Users/gableroux/repos/hubot/node_modules/hubot-github-repo-event-notifier/src/github-repo-event-notifier: SyntaxError: reserved word "function"
  at exports.throwSyntaxError (/Users/gableroux/repos/hubot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/helpers.js:197:13)
  at Lexer.exports.Lexer.Lexer.error (/Users/gableroux/repos/hubot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/lexer.js:778:14)
  at Lexer.exports.Lexer.Lexer.identifierToken (/Users/gableroux/repos/hubot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/lexer.js:102:16)
  at Lexer.exports.Lexer.Lexer.tokenize (/Users/gableroux/repos/hubot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/lexer.js:30:25)
  at exports.compile.compile (/Users/gableroux/repos/hubot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:35:36)
  at Object.loadFile (/Users/gableroux/repos/hubot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:176:14)
  at Module.load (/Users/gableroux/repos/hubot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Robot.loadFile (/Users/gableroux/repos/hubot/node_modules/hubot/src/robot.coffee:250:9, <js>:175:20)
  at /Users/gableroux/repos/hubot/node_modules/hubot-github-repo-event-notifier/index.coffee:12:11, <js>:26:33
  at FSReqWrap.cb [as oncomplete] (fs.js:226:19)
```

I've switched to `1.4.0` and didn't get the error.

**Comment by GabLeRoux** [comment]
My fix attempt did not work yet, I tested with a push hook example and got
```
Processing event type push...
Whoa, I got an error: TypeError: undefined is not a function
github repo event notifier error: TypeError: undefined is not a function. Request: [object Object]
```

(same request was working with `1.4.0`. I'll go with this version for now :)

**Comment by patcon** [comment]
thoughts @geekgonecrazy?

Not using the plugin myself right now, and no time to troubleshoot, so I'll unfortunately need to revert that last PR if we can't diagnose. Any help or insight is appreciated!

**Comment by patcon** [comment]
@GabLeRoux how did you configure this plugin btw? also, thanks for reporting!

**Comment by geekgonecrazy** [comment]
Yikes.. Looks like the code I cherry picked.  I'll take a quick stab at reproducing / fixing.

**Comment by GabLeRoux** [comment]
Thanks! I didn't do much as you can see, grabbed latest code, ran with all actions in env var and hubot didn't start.

You can have a look to my fork, seems like there's some javascript mixed in the coffe, I've fixed it but still having a problem when receiving a push event. Don't have computer right now, but I'll give a hand if you need ;)

**Comment by geekgonecrazy** [comment]
@GabLeRoux yeah that was for sure my fault.  Didn't test well.  Quickly cherry picked from a closed pull request, so I could get the other changes upstream.  

This should do the trick.  Tested it out better this time.  If you wanna give a try.  So we can try and quickly get this fixed  :)
